name: Run PHPCS - WordPressVIPMinimum

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    phpcs:
        name: Run PHP_CodeSniffer
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Set up PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: '8.1'
                  extensions: mbstring, xml
                  coverage: none

            - name: Initialize Composer (if missing)
              run: |
                  if [ ! -f "composer.json" ]; then
                    composer init --name="vip/wordpressvip" --require-dev=automattic/vipwpcs --no-interaction
                  fi

            - name: Require VIP WPCS and additional sniffs
              run: |
                  composer require --dev \
                    automattic/vipwpcs \
                    wp-coding-standards/wpcs \
                    phpcsstandards/phpcsutils \
                    phpcsstandards/phpcsextra \
                    sirbrillig/phpcs-variable-analysis

            - name: Set PHPCS installed paths
              run: vendor/bin/phpcs --config-set installed_paths vendor/wp-coding-standards/wpcs,vendor/automattic/vipwpcs,vendor/phpcsstandards/phpcsutils,vendor/phpcsstandards/phpcsextra,vendor/sirbrillig/phpcs-variable-analysis

            - name: Show installed coding standards
              run: vendor/bin/phpcs -i

            - name: Run PHPCS with WordPressVIPMinimum
              run: vendor/bin/phpcs --standard=WordPressVIPMinimum --extensions=php,js,css wp-content/
