name: Run PHPCS - WordPressVIPMinimum

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    phpcs:
        name: Run PHP_CodeSniffer
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Code
              uses: actions/checkout@v3

            - name: Set up PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: '8.1'
                  extensions: mbstring, xml
                  coverage: none

            - name: Cache Composer dependencies
              uses: actions/cache@v3
              with:
                  path: ~/.composer/cache
                  key: composer-${{ runner.os }}-${{ hashFiles('**/composer.lock') }}
                  restore-keys: |
                      composer-${{ runner.os }}-

            - name: Validate composer.json and composer.lock
              run: composer validate --strict

            - name: Install Composer dependencies
              run: composer install --no-progress --prefer-dist

            - name: Set PHPCS installed paths
              run: |
                  vendor/bin/phpcs --config-set installed_paths \
                    vendor/wp-coding-standards/wpcs,\
                    vendor/phpcsstandards/phpcsutils,\
                    vendor/phpcsstandards/phpcsextra,\
                    vendor/sirbrillig/phpcs-variable-analysis

            - name: Show installed coding standards
              run: vendor/bin/phpcs -i

            - name: Run PHPCS with WordPressVIPMinimum
              run: |
                  vendor/bin/phpcs --standard=WordPressVIPMinimum --extensions=php wp-content/
